# Первая выгрузка → DataFrame

Один CSV, 238 уникальных вакансий, 55 колонок. Наблюдения за 21.10.2026 (МСК): 6 профессий, 3 города.

Нужен `pandas`. Параметры карточек уже в отдельных колонках. Архив и паспорт для загрузки не нужны.

In [1]:
import pandas as pd
from pathlib import Path

# Работает при запуске из корня репозитория и из папки ML.
file = Path("Data/first_export_2026-10-21.csv")
if not file.exists():
    file = Path("..") / file

df = pd.read_csv(file, dtype={"id": "string"})
df.head()

,id,city,profession,segments,title,salary_raw,employer_name_observed,location_observed,source_url,observed_at,...,Количество рабочих дней в неделю,Способ доставки,Вид доставки,Где предстоит работать,Разряд,read_status_parameters,read_status_description,read_status_employer,read_status_location,read_limitations
0,1092399524,Москва,Водитель грузового транспорта,truck_driver_moscow,Водитель экспедитор на Газель некст,100 000 — 150 000 ₽ \nна руки,Андрей,"Москва, Северный административный округ, район...",https://www.avito.ru/moskva/vakansii/voditel_e...,2026-10-21T00:55:41.736Z,...,NaN,NaN,NaN,NaN,NaN,observed,observed,observed,observed,Employer profile was not opened.
1,1412038579,Москва,Водитель грузового транспорта,truck_driver_moscow,"Водитель автобетоносмесителя (абс, миксера)",240 000 — 400 000 ₽ \nна руки,Андрей,"Москва, пр. Воскресенские Ворота, Охотный ряд;...",https://www.avito.ru/moskva/vakansii/voditel_a...,2026-10-21T06:29:11.841Z,...,NaN,NaN,NaN,NaN,NaN,observed,observed,observed,observed,Seller profile was not opened.
2,1816151640,Москва,Водитель грузового транспорта,truck_driver_moscow,Водитель автобетоносмесителя вахта 15/15,от 160 000 ₽ \nна руки,Бетонное производство БАВ ГРУПП,"Москва, Филёвская линия Кунцевская до 5 мин.Пи...",https://www.avito.ru/moskva/vakansii/voditel_a...,2026-10-21T00:49:40.156Z,...,NaN,NaN,NaN,NaN,NaN,observed,observed,observed,observed,Employer profile was not opened.
3,1938209111,Санкт-Петербург,Продавец,seller_spb,Продавец в магазин обуви,4 000 — 5 000 ₽ \nза смену на руки,preyo shoes,"Санкт-Петербург, Садовая ул., 32 Сенная площадь",https://www.avito.ru/sankt-peterburg/vakansii/...,2026-10-21T07:34:04.667Z,...,NaN,NaN,NaN,NaN,NaN,rendered_fields_observed_not_fully_verified,observed_in_raw; snapshot_text_node_clipped,observed_snapshot_and_public_aux,observed_snapshot,"Офлайн-сверка подтвердила ID/URL, заголовок, з..."
4,2085210675,Екатеринбург,Водитель грузового транспорта,truck_driver_ekb,Водитель самосвала,150 000 — 200 000 ₽,"ООО ""ТТК""","Свердловская обл., Екатеринбург, пл. 1905 года",https://www.avito.ru/ekaterinburg/vakansii/vod...,2026-10-21T07:02:12.277Z,...,NaN,NaN,NaN,NaN,NaN,observed,observed,observed,observed,employer_profile_not_opened

In [2]:
df.shape  # строки, колонки

(238, 55)

In [3]:
df[["id", "city", "profession", "title", "salary_raw", "График", "Опыт работы"]].head()

,id,city,profession,title,salary_raw,График,Опыт работы
0,1092399524,Москва,Водитель грузового транспорта,Водитель экспедитор на Газель некст,100 000 — 150 000 ₽ \nна руки,Гибкий,Более 3 лет
1,1412038579,Москва,Водитель грузового транспорта,"Водитель автобетоносмесителя (абс, миксера)",240 000 — 400 000 ₽ \nна руки,Вахта,Без опыта
2,1816151640,Москва,Водитель грузового транспорта,Водитель автобетоносмесителя вахта 15/15,от 160 000 ₽ \nна руки,Вахта,Более 1 года
3,1938209111,Санкт-Петербург,Продавец,Продавец в магазин обуви,4 000 — 5 000 ₽ \nза смену на руки,Сменный,Более 3 лет
4,2085210675,Екатеринбург,Водитель грузового транспорта,Водитель самосвала,150 000 — 200 000 ₽,Вахта,Более 1 года

In [4]:
moscow = df.loc[df["city"].eq("Москва")]
moscow[["title", "salary_raw", "График"]].head()

,title,salary_raw,График
0,Водитель экспедитор на Газель некст,100 000 — 150 000 ₽ \nна руки,Гибкий
1,"Водитель автобетоносмесителя (абс, миксера)",240 000 — 400 000 ₽ \nна руки,Вахта
2,Водитель автобетоносмесителя вахта 15/15,от 160 000 ₽ \nна руки,Вахта
7,Грузчик-комплектовщик,от 160 900 ₽ \nна руки,Сменный
16,Водитель категории С,7 700 — 11 000 ₽ \nза смену на руки,Гибкий

In [5]:
df["city"].value_counts()

city
Москва             119
Екатеринбург        60
Санкт-Петербург     59
Name: count, dtype: int64

Дальше работайте с `df`: выбирайте колонки, фильтруйте строки, стройте признаки. Все названия колонок: `df.columns.tolist()`.

Пустая ячейка — неизвестное значение. `salary_raw` — исходная строка, период суммы не пересчитывался. 158 карточек имеют `full_parameters_read=False`: их сохранённые поля доступны, но полнота чтения не подтверждена.

Две вакансии входят и в «Продавец», и в «Кассир». В `profession` и `segments` их значения разделены `; `; строки не дублируются. Всего 238 вакансий и 240 включений. Подсчёт по `profession` считает сочетания; отдельный сегмент можно выбрать через `df["segments"].str.split("; ").apply(lambda values: "seller_moscow" in values)`.

[Подробности колонок и происхождения](../Data/README.md). [Прежний вариант с паспортом](01_load_with_passport.ipynb) сохранён отдельно.